GET http://127.0.0.1:8000/api/payment HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "request_id": "2",
    "payment_id": "2",
    "sum": "2000",
    "email": "jawadrumah@gmail.com"
}
###
GET http://127.0.0.1:8000/api/users HTTP/1.1
Content-Type: application/json
Accept: application/json

###
POST http://127.0.0.1:8000/api/users HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "name": "Abduljawad Ibrahim Narumah",
    "email": "admin@demo.com",
    "phone_number": "07066352444",
    "password": "password",
    "user_type_id": 2,
    "years_experiance": 5,
    "image": ""
}

###
PUT http://127.0.0.1:8000/api/users/3 HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "name": "Abduljawad Ibrahim Narumah",
    "email": "admin@demo.com",
    "phone_number": "07066352444",
    "password": "password",
    "user_type_id": 2,
    "years_experiance": 5,
    "image": ""
}
###
GET http://127.0.0.1:8000/api/users/3 HTTP/1.1
Content-Type: application/json
Accept: application/json
###
DELETE http://127.0.0.1:8000/api/users/2 HTTP/1.1
Content-Type: application/json
Accept: application/json

###
POST http://127.0.0.1:8000/api/car-product HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "name": "Benz",
    "description": "description"
}
###
PUT http://127.0.0.1:8000/api/car-product/2 HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "name": "Honda",
    "description": "description"
}
###
GET http://127.0.0.1:8000/api/car-product/2 HTTP/1.1
Content-Type: application/json
Accept: application/json
###
DELETE http://127.0.0.1:8000/api/car-product/1 HTTP/1.1
Content-Type: application/json
Accept: application/json
###
GET http://127.0.0.1:8000/api/request HTTP/1.1
Content-Type: application/json
Accept: application/json
###
POST http://127.0.0.1:8000/api/request HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "user_id": 2,
    "car_product_id": 2,
    "mechanic_id": 3,
    "description": "description"
}
###
PUT http://127.0.0.1:8000/api/request/2 HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "user_id": 2,
    "car_product_id": 2,
    "mechanic_id": 3,
    "description": "description"
}
###
DELETE http://127.0.0.1:8000/api/request/1 HTTP/1.1
Content-Type: application/json
Accept: application/json
###
GET http://127.0.0.1:8000/api/areaspecialization HTTP/1.1
Content-Type: application/json
Accept: application/json
###
POST http://127.0.0.1:8000/api/areaspecialization HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "user_id": 2,
    "car_product_id": 2,
    "specialization_area_id": 3
}
###
PUT http://127.0.0.1:8000/api/areaspecialization/2 HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "user_id": 2,
    "car_product_id": 2,
    "specialization_area_id": 3
}

###
GET http://127.0.0.1:8000/api/areaspecialization/3 HTTP/1.1
Content-Type: application/json
Accept: application/json
###
GET http://127.0.0.1:8000/api/areaspecialization/2 HTTP/1.1
Content-Type: application/json
Accept: application/json
###
DELETE http://127.0.0.1:8000/api/areaspecialization/1 HTTP/1.1
Content-Type: application/json
Accept: application/json
###
DELETE http://127.0.0.1:8000/api/areaspecialization/5 HTTP/1.1
Content-Type: application/json
Accept: application/json

###
POST http://127.0.0.1:8000/api/auth/login HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "email": "super@demo.com",
    "password": "password"
}

###
POST http://127.0.0.1:8000/api/auth/logout HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|6pApueDorzpf7eA7yNWoLBvpPTweD9OodOPxmcBX
